[cmdcomp]
version = "2"

[app]
name = "cliname"
alias = "cliname2"

[root]
[root.arguments.--verbose]
type = "flag"
description = "verbose output."

[root.arguments.--no-verbose]
type = "flag"
description = "no verbose output."

[root.arguments.--version]
type = "flag"
alias = "-V"
description = "print version."

[root.arguments.--config]
type = "file"
description = "config file."

[root.arguments.--help]
type = "flag"
description = "print help."

[root.subcommands.list]
alias = "ls"
description = "list project files."

[root.subcommands.list.arguments.--all]
type = "flag"
alias = "-a"
description = "list all files."

[root.subcommands.list.arguments."*"]
type = "file"
description = "list files."

[root.subcommands.cd]
description = "cd project directory."

[root.subcommands.cd.arguments.-P]
type = "flag"
description = "physical directory."

[root.subcommands.cd.arguments.1]
type = "file"
base_path = "$HOME"
description = "change project directory."

[root.subcommands.test]
description = "test command."

[root.subcommands.test.subcommands.rubocop]
description = "run rubocop."

[root.subcommands.test.subcommands.rubocop.arguments.--auto-correct]
type = "flag"
alias = "-A"
description = "auto correct."

[root.subcommands.test.subcommands.pytest]
description = "run pytest."
