# It's still in draft.
cmdcomp:
  version: "2"
app:
  name: "cliname"
  alias: "cliname2"
root:
  arguments:
    --verbose:
      type: flag
      description: "verbose output."
    --no-verbose:
      type: flag
      description: "no verbose output."
    --version:
      type: flag
      alias: "-V"
      description: "print version."
    --help:
      type: flag
      description: "print help."
  subcommands:
    list:
      alias: "ls"
      description: "list project files."
      arguments:
        --all:
          type: flag
          alias: "-a"
          description: "list all files."
    cd:
      description: "cd project directory."
      arguments:
        1:
          type: file
          description: "change project directory."
    test:
      description: "test command."
      subcommands:
        rubocop:
          description: "run rubocop."
          arguments:
            --auto-correct:
              type: flag
              alias: "-A"
              description: "auto correct."
        pytest:
          description: "run pytest."
