cmdcomp:
  version: "2"
app:
  name: "cliname"
  alias: "cliname2"
root:
  arguments:
    1: "arg1"
    2:
      type: values
      candidates:
        - "cand1"
        - "cand2"
    3:
      candidates:
        cand3:
          description: "cand3 description"
          value: "cand3"
        cand4: "cand4"
    --file:
      type: file
      base_path: "~"
