cmdcomp:
  version: "2"
app:
  name: "cliname"
  alias: "cliname2"
root:
  arguments:
    1: "arg1"
    2:
      type: values
      candidates:
        - "cand1"
        - "cand2"
    --file:
      type: file
      base_path: "~"
