cmdcomp:
  version: "2"
app:
  name: "cliname"
  alias: "cliname2"
root:
  arguments:
    1: "arg1"
    2: ["arg1", "arg2", "arg3"]
    3:
      - value: "arg1"
        description: "arg1 description"
      - value: "arg2"
        description: "arg2 description"
    --file:
      type: file
      alias: "-f"
      base_path: "~"
