[tool.poetry]
name = "cmdcomp"
version = "2.0.0"
description = "cmdcomp is a cli tool completion generator for shell."
authors = ["Yasutanium <yassun4dev@outlook.com>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/yassun4dev/cmdcomp"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.scripts]
cmdcomp = "cmdcomp.main:main"

[tool.taskipy.tasks]
generate-json-schema = "python tasks/generate_json_schema.py > docs/config.schema.json"
generate-completion = "register-python-argcomplete cmdcomp"
test = "pytest"
format = "black --target-version py310 ."
lint = "pyright cmdcomp/** tests/**"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.0"
jinja2 = "^3.1.2"
mergedeep = "^1.3.4"
pyyaml = "^6.0"
rich = "^13.4.2"
argcomplete = "^3.1.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.2"
pyright = "^1.1.300"
taskipy = "^1.10.4"
pytest-asyncio = "^0.21.0"
ipython = "^8.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
# make it compatible with black
line_length = 88
multi_line_output = 3
profile = "black"

[tool.flake8]
max-line-length = 200
ignore = ["E203"]
extend-ignore = ["W503"]

[tool.pyright]
exclude = ["**/__pycache__"]
reportPrivateImportUsage = "none"
reportUnusedImport = true

[tool.mypy]
[[tool.mypy.overrides]]
ignore_missing_imports = true
module = []
