[cmdcomp]
version = "2"

[app]
name = "cliname"
alias = ["cliname2"]

[root]
[root.arguments.--verbose]
type = "flag"
description = "verbose output."

[root.arguments.--no-verbose]
type = "flag"
description = "no verbose output."

[root.arguments.--version]
type = "flag"
alias = "-V"
description = "print version."

[root.arguments.--config]
type = "file"
description = "config file."

[root.arguments.--type]
type = "select"
description = "config file type."
options = ["json", "toml"]

[root.arguments.--help]
type = "flag"
description = "print help."

[root.subcommands.list]
alias = "ls"
description = "list project files."

[root.subcommands.list.arguments.--all]
type = "flag"
alias = "-a"
description = "list all files."

[root.subcommands.list.arguments."*"]
type = "file"
description = "list files."

[root.subcommands.cd]
description = "cd project directory."

[root.subcommands.cd.arguments.-P]
type = "flag"
description = "physical directory."

[root.subcommands.cd.arguments.1]
type = "file"
base_path = "$HOME"
description = "change project directory."

[root.subcommands.scripts]
description = "operate scripts."
[root.subcommands.scripts.subcommands.run]
description = "run script."

[root.subcommands.scripts.subcommands.run.arguments.--all]
type = "flag"
alias = "-a"
description = "run all scripts."

[root.subcommands.scripts.subcommands.run.arguments."*"]
type = "command"
description = "run script."
execute = "echo 'script1.sh script2.sh script3.sh'"

[root.subcommands.git]
type = "delegate"
description = "git command."
target = ["git"]

[root.subcommands.git.arguments.--envname]
type = "select"
options = ["dev", "prd"]

[root.subcommands.test]
description = "test command."

[root.subcommands.test.subcommands.rubocop]
description = "run rubocop."

[root.subcommands.test.subcommands.rubocop.arguments.--auto-correct]
type = "flag"
alias = "-A"
description = "auto correct."

[root.subcommands.test.subcommands.pytest]
description = "run pytest."
