cmdcomp:
  version: "2"
app:
  name: "cliname"
  alias: "cliname2"
root:
  arguments:
    --verbose:
      type: flag
      description: "verbose output."
    --no-verbose:
      type: flag
      description: "no verbose output."
    --version:
      type: flag
      alias: "-V"
      description: "print version."
    --config:
      type: file
      description: "config file."
    --type:
      type: select
      description: "config file type."
      options:
        - json
        - toml
    --help:
      type: flag
      description: "print help."
  subcommands:
    list:
      alias: "ls"
      description: "list project files."
      arguments:
        --all:
          type: flag
          alias: "-a"
          description: "list all files."
        "*":
          type: file
          description: "list files."
    cd:
      description: "cd project directory."
      arguments:
        -P:
          type: flag
          description: "physical directory."
        1:
          type: file
          base_path: $HOME
          description: "change home directory."
    scripts:
      description: "operate scripts."
      subcommands:
        run:
          description: "run script."
          arguments:
            --all:
              type: flag
              alias: "-a"
              description: "run all scripts."
            "*":
              type: command
              description: "run script."
              execute: "echo 'script1.sh script2.sh script3.sh'"
    git:
      type: relay
      description: git command.
      target: "git"
    test:
      description: "test command."
      subcommands:
        rubocop:
          description: "run rubocop."
          arguments:
            --auto-correct:
              type: flag
              alias: "-A"
              description: "auto correct."
        pytest:
          description: "run pytest."
