[cmdcomp]
version = "1"

[app]
name = "your_cli_command_name"

[root]
options = ["-h", "--help", "--version"]

[root.subcommands.welcome]

[root.subcommands.list]
options = ["-a"]
alias = "ls"

[root.subcommands.execute]
options = { type = "command", execute = "your_app_name ps -s" }
alias = ["restart", "shell", "log"]

[root.subcommands.cd]
options = { type = "file", base_path = "$(cd $(dirname $0); pwd)/../apps" }

[root.subcommands.test.subcommands.rubocop]
options = ["-A"]

[root.subcommands.and_normal_options_work]
options = ["-h", "--help"]
subcommands = { foo = {}, bar = {} }
