cmdcomp:
  version: "1"
app:
  name: "your_cli_command_name"
  alias: "cli_alias_name"
root:
  options: ["-h", "--help", "--version"]
  subcommands:
    welcome:
    list:
      alias: "ls"
      options: ["-a"]
    execute:
      alias: ["restart", "shell", "log"]
      options:
        type: "command"
        execute: "your_app_name ps -s"
    cd:
      options:
        type: "file"
        base_path: "$(cd $(dirname $0); pwd)/../apps"
    test:
      subcommands:
        rubocop:
          options: ["-A"]
    and_normal_options_work:
      options: ["-h", "--help"]
      subcommands:
        foo:
        bar:
