cmdcomp:
  version: "2"
app:
  name: "mycli"
root:
  arguments:
    --verbose:
      type: flag
      description: "verbose output."
    --help:
      type: flag
      description: "print help."
  subcommands:
    gcloud:
      type: delegate
      description: "gcloud command."
      target: [gcloud]
    gcs:
      type: delegate
      description: "gcs command."
      target: [gcloud, storage]
    composer-operation:
      type: delegate
      description: "composer operation command."
      target: [gcloud, composer, operations]
    git:
      type: delegate
      description: "git command."
      target: [git]
    test:
      description: "test command."
      subcommands:
        rubocop:
          description: "run rubocop."
          arguments:
            --auto-correct:
              type: flag
              alias: "-A"
              description: "auto correct."
        pytest:
          description: "run pytest."
